"""Update Member model with full fields

Revision ID: 0551fc42779f
Revises: 8897e1de1979
Create Date: 2024-09-12 22:36:27.251921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0551fc42779f'
down_revision = '8897e1de1979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('birth_month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('birth_day', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('photo')
        batch_op.drop_column('district')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('birth_day')
        batch_op.drop_column('birth_month')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('register_date')

    # ### end Alembic commands ###
