"""Update models

Revision ID: 689b2f0b3cf7
Revises: dbbc0cc67c62
Create Date: 2024-09-25 13:35:43.163744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689b2f0b3cf7'
down_revision = 'dbbc0cc67c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 임시 테이블 삭제 시도를 조건부로 변경
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint('uq_member_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_email', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # 임시 테이블 생성 부분 제거
    # ### end Alembic commands ###
